#!/bin/bash
# Get pixel values at given position
if [ $# -ne 2 ] || ! [[ $1 =~ ^[0-9]+$ ]] || ! [[ $2 =~ ^[0-9]+$ ]]
then
    echo "Usage gpixat <x> <y>"
    exit 1
fi 
xdotool mousemove 0 0 2>/dev/null
sleep 0.2
grabc&
xdotool mousemove "$1" "$2" 2>/dev/null

xdotool click 1 2>/dev/null
