#!bin/bash

#ffmpeg -f alsa -i default "$1.mp3" # only sound
ffmpeg -y \
  -f x11grab \
  -framerate 45 \
  -s 1920x1080 \
  -i :0.0 \
  -f alsa \
  -i default out.mkv 2>/dev/null # both sound and video
